SELECT * FROM CUSTOMERS ;
SELECT FULL_NAME, city FROM CUSTOMERS ;
SELECT * FROM CUSTOMERS where CITY='Cairo';
SELECT * FROM CUSTOMERS where EMAIL IS NULL;
SELECT * FROM CUSTOMERS ORDER BY JOIN_DATE DESC;
SELECT DISTINCT CITY FROM CUSTOMERS ;
SELECT * FROM CUSTOMERS  ORDER BY JOIN_DATE ASC FETCH FIRST 3 ROWS ONLY;

SELECT * FROM PRODUCTS ;
SELECT * FROM PRODUCTS WHERE CATEGORY IN ('Electronics','Accessories') ;
SELECT * FROM PRODUCTS WHERE PRICE BETWEEN 200 and 1500 ;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE '%Stand%' ;
SELECT * FROM PRODUCTS  ORDER BY PRICE DESC ;
SELECT DISTINCT CATEGORY FROM PRODUCTS  ;
SELECT * FROM PRODUCTS ORDER by price DESC fetch first 2 rows only ;

SELECT * FROM ORDERS ;
SELECT * FROM orders WHERE status IN ('PAID', 'PENDING');
SELECT * FROM orders WHERE ORDER_DATE BETWEEN  date'2025-03-21' and date'2025-03-26' ;
SELECT * FROM orders WHERE status LIKE 'P%';
SELECT * FROM orders ORDER BY order_date DESC;
SELECT DISTINCT status FROM orders;
SELECT * FROM orders ORDER BY total_amount DESC FETCH FIRST 3 ROWS ONLY;
