ALTER TABLE SANDBOX_LOGS ADD log_level VARCHAR2(20);


UPDATE SANDBOX_LOGS
SET LOG_LEVEL='INFO'
WHERE LOG_ID =1;

UPDATE SANDBOX_LOGS
SET LOG_LEVEL='WARN'
WHERE LOG_ID =2;

TRUNCATE TABLE sandbox_logs;

DROP TABLE sandbox_logs;
